### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by yhl48** [aschethor/Spline_PINN#1]
Hi, I have a few questions regarding the methodology to which I was hoping you could provide some clarifications.

1. Since the grid is regular for CNN, let's say for the sake of argument we have an arbitrarily large domain with an obstacle near the inlet; with an appropriate pair of viscosity and density in a laminar profile, the pressure and velocity for the large part of the domain away from the obstacle would be more or less constant along the x-axis, and that would mean we are wasting resources on that part of the domain. It looks to me that it is an inherent weakness of the method, could you confirm or explain if there is a workaround?
2. Does the model work for compressible Navier Stokes?
3. Did you try any interpolation methods other than Hermite splines and how did they perform?
4. Is the interpolation using Hermite splines too smooth for high Reynolds number?

Thank you!

**Comment by wandeln** [comment]
Hi Yi Heng,

thanks for showing interest into our work! :)

Regarding your questions:
1. Yes, if your problem setup requires different levels of detail within the fluid domain, an approach based on a uniform grid might not be the best solution. As we mentioned in our conclusions, this could be addressed in the future using a multigrid approach.
2. We haven't tested our approach for the compressible Navier Stokes equation yet but we believe this should work out as well. Note that for the compressible version you cannot make use of a vector-potential for the velocity field anymore so a few additional modifications might be required.
3. In this work, we focused only on Hermite splines since they guarantee that the derivatives of the provided fields are of bounded variation (see argument in Figure 1 as well as the section on Hermite splines and the physics-informed loss). Futhermore, Hermite splines have small interpolation kernels and thus can be efficiently computed.
4. For very high Reynolds-numbers one might has to adapt the grid resolution in order to properly capture also tiny vortices / turbulences.

I hope, I was able to answer you questions. If there are further questions / remarks, feel free to contact me again!

Best regards,
Nils

**Comment by yhl48** [comment]
Thank you, that really cleared things up, appreciate it!

A follow-up question: multigrid approach sounds interesting, but there doesn't seem to be a rich literature on that upon a quick lookup on google. Do you have any papers on multigrid CNNs that could be good references?

**Comment by wandeln** [comment]
We haven't thought about this multigrid idea in full detail yet. Maybe the "MgNet"-Paper by Juncai He and Jinchao Xu (https://arxiv.org/abs/1901.10415) could be a good starting point if you would like to go into this direction :)

**Comment by yhl48** [comment]
Thank you!
